name: security

on:
  push:
    branches:
      - '*.x'
  pull_request:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  security:
    name: Security on PHP ${{ matrix.php-version }} (Ubuntu 24.04)
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        php-version:
          - '8.3'
          - '8.4'
          - '8.5'
    steps:
      - name: Setup PHP ${{ matrix.php-version }}
        uses: shivammathur/setup-php@44454db4f0199b8b9685a5d763dc37cbf79108e1
        with:
          php-version: ${{ matrix.php-version }}

      - name: Checkout Repository
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8

      - name: Cache Composer Packages
        uses: actions/cache@9255dc7a253b0ccc959486e2bca901246202afeb
        with:
          path: ~/.composer/cache
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Install Dependencies
        run: composer install --prefer-dist --no-interaction --no-progress --dev

      - name: Run Composer Audit
        env:
          COMPOSER_PROCESS_TIMEOUT: 300
        run: composer audit
