name: test

on:
  push:
    branches:
      - '*.x'
  pull_request:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  test:
    name: PHPUnit ${{ matrix.phpunit-version }} on PHP ${{ matrix.php-version }} (Ubuntu 24.04)
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        php-version:
          - '8.3'
          - '8.4'
          - '8.5'
        phpunit-version:
          - '13.0'
    steps:
      - name: Setup PHP ${{ matrix.php-version }}
        uses: shivammathur/setup-php@44454db4f0199b8b9685a5d763dc37cbf79108e1
        with:
          php-version: ${{ matrix.php-version }}
          coverage: pcov

      - name: Checkout Repository
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8

      - name: Require PHPUnit ${{ matrix.phpunit-version }}
        run: composer require --dev phpunit/phpunit:^${{ matrix.phpunit-version }} --with-all-dependencies

      - name: Install Dependencies
        run: composer update --prefer-dist --no-interaction --no-progress

      - name: Run PHP_CodeSniffer
        run: vendor/bin/phpcs --standard=phpcs.xml.dist

      - name: Run PHPUnit ${{ matrix.phpunit-version }}
        run: vendor/bin/phpunit --configuration=phpunit.xml.dist --coverage-xml=build/coverage-xml

      - name: Upload Code Coverage to Codecov
        uses: codecov/codecov-action@57e3a136b779b570ffcdbf80b3bdc90e7fab3de2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: build/coverage-xml/coverage.xml
